version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "monthly"
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
  - ryu22e
  assignees:
  - ryu22e
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: "monthly"
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  target-branch: main
  reviewers:
  - ryu22e
  assignees:
  - ryu22e
  groups:
    sphinx-dependencies:
      dependency-type: "production"
      patterns:
        - "Sphinx"
        - "sphinx-*"
        - "sphinxcontrib-*"
        - "myst-parser"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
    time: "08:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  reviewers:
  - ryu22e
  assignees:
  - ryu22e
