%%{init: {"themeVariables": {"pieLegendTextSize": "9px"}} }%%
pie
    title About Python Experience
    "for the first time at all" : 59.523809523809526
    "Occasional use" : 27.380952380952383
    "Just a little" : 10.912698412698413
    "use frequently" : 2.1825396825396823
